// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package shared

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"strings"

	templpkg "github.com/a-h/templ"
	"wedding-invitation-go/internal/invitation"
)

// ============================================
// SOCIAL LINKS TEXT — teks label fallback
// ============================================

type SocialLinksText struct {
	Instagram string
	WhatsApp  string
	YouTube   string
}

var SocialLinksTextDefault = SocialLinksText{
	Instagram: "Instagram",
	WhatsApp:  "WhatsApp",
	YouTube:   "YouTube",
}

// ============================================
// HELPER: Ekstrak info dari URL
// ============================================

// getInstagramHandle — extract @username dari URL IG
// Contoh: "https://instagram.com/wedding_event" → "@wedding_event"
func getInstagramHandle(url string) string {
	if url == "" {
		return ""
	}
	// Hapus trailing slash
	url = strings.TrimSuffix(url, "/")
	// Hapus query string
	if idx := strings.Index(url, "?"); idx != -1 {
		url = url[:idx]
	}
	// Ambil bagian setelah "/"
	parts := strings.Split(url, "/")
	if len(parts) == 0 {
		return ""
	}
	handle := parts[len(parts)-1]
	if handle == "" {
		return ""
	}
	// Kalau bukan @, tambahkan @
	if !strings.HasPrefix(handle, "@") {
		handle = "@" + handle
	}
	return handle
}

// getWhatsAppNumber — format nomor WA
// Contoh: "6281234567890" → "+62 812-3456-7890"
func getWhatsAppNumber(phone string) string {
	if phone == "" {
		return ""
	}
	// Hapus non-digit
	var digits []rune
	for _, c := range phone {
		if c >= '0' && c <= '9' {
			digits = append(digits, c)
		}
	}
	phone = string(digits)
	if phone == "" {
		return ""
	}
	// Kalau mulai dengan 0, ganti 62
	if strings.HasPrefix(phone, "0") {
		phone = "62" + phone[1:]
	}
	// Kalau tidak mulai dengan +, tambahkan +
	if !strings.HasPrefix(phone, "+") {
		phone = "+" + phone
	}
	// Format: +62 812-3456-7890
	// Ambil kode negara (2-3 digit awal)
	if len(phone) < 4 {
		return phone
	}
	// Kode negara: +62 (2 digit setelah +)
	countryCode := phone[:3] // "+62"
	rest := phone[3:]        // "81234567890"

	// Bagi rest jadi grup: 3-4-4
	var formatted strings.Builder
	formatted.WriteString(countryCode)
	formatted.WriteString(" ")

	if len(rest) >= 3 {
		formatted.WriteString(rest[:3])
		rest = rest[3:]
		if len(rest) > 0 {
			formatted.WriteString("-")
		}
	}
	if len(rest) >= 4 {
		formatted.WriteString(rest[:4])
		rest = rest[4:]
		if len(rest) > 0 {
			formatted.WriteString("-")
		}
	}
	if len(rest) > 0 {
		formatted.WriteString(rest)
	}

	return formatted.String()
}

// getYouTubeDisplay — extract display text dari URL YouTube
// Contoh: "https://youtube.com/watch?v=xxx" → "youtube.com" atau nama channel
func getYouTubeDisplay(url string) string {
	if url == "" {
		return ""
	}
	// Coba extract nama channel dari format:
	// - https://youtube.com/@channelname
	// - https://youtube.com/c/channelname
	// - https://youtube.com/channel/UC...
	if strings.Contains(url, "/@") {
		parts := strings.Split(url, "/@")
		if len(parts) > 1 {
			name := parts[1]
			if idx := strings.IndexAny(name, "/?"); idx != -1 {
				name = name[:idx]
			}
			return "@" + name
		}
	}
	if strings.Contains(url, "/c/") {
		parts := strings.Split(url, "/c/")
		if len(parts) > 1 {
			name := parts[1]
			if idx := strings.IndexAny(name, "/?"); idx != -1 {
				name = name[:idx]
			}
			return name
		}
	}
	// Fallback: "youtube.com"
	return "youtube.com"
}

// ============================================
// SOCIAL LINKS — icon + teks dinamis
// ============================================
func SocialLinks(data *invitation.TemplateData, text SocialLinksText) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"footer-social\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if data.EventInstagram != "" {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<a href=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var2 templ.SafeURL
			templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinURLErrs(templpkg.SafeURL(data.EventInstagram))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/invitations/shared/social_links.templ`, Line: 159, Col: 50}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "\" target=\"_blank\" rel=\"noopener\" title=\"Instagram Acara\"><i class=\"bi bi-instagram\"></i> <span>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var3 string
			templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(getInstagramHandle(data.EventInstagram))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/invitations/shared/social_links.templ`, Line: 161, Col: 51}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "</span></a> ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		if data.Whatsapp != "" {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "<a href=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var4 templ.SafeURL
			templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinURLErrs(templpkg.SafeURL("https://wa.me/" + data.Whatsapp))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/invitations/shared/social_links.templ`, Line: 165, Col: 63}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "\" target=\"_blank\" rel=\"noopener\" title=\"WhatsApp\"><i class=\"bi bi-whatsapp\"></i> <span>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var5 string
			templ_7745c5c3_Var5, templ_7745c5c3_Err = templ.JoinStringErrs(getWhatsAppNumber(data.Whatsapp))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/invitations/shared/social_links.templ`, Line: 167, Col: 44}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var5))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "</span></a> ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		if data.Youtube != "" {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, "<a href=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var6 templ.SafeURL
			templ_7745c5c3_Var6, templ_7745c5c3_Err = templ.JoinURLErrs(templpkg.SafeURL(data.Youtube))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/invitations/shared/social_links.templ`, Line: 171, Col: 43}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var6))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 9, "\" target=\"_blank\" rel=\"noopener\" title=\"YouTube\"><i class=\"bi bi-youtube\"></i> <span>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var7 string
			templ_7745c5c3_Var7, templ_7745c5c3_Err = templ.JoinStringErrs(getYouTubeDisplay(data.Youtube))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/invitations/shared/social_links.templ`, Line: 173, Col: 43}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var7))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 10, "</span></a>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 11, "</div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
