// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package admin

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "wedding-invitation-go/internal/models"

// DashboardContent — konten halaman dashboard admin
// Ini yang dirender di dalam layout AdminLayout
func DashboardContent(
	totalClients int,
	totalStaff int,
	totalProjects int,
	totalTemplates int,
	totalDraft int,
	totalPublished int,
	totalRsvp int,
	totalViews int,
	recentProjects []models.Project,
	user models.User,
) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"d-flex flex-column flex-md-row justify-content-between align-items-start align-items-md-center mb-4 gap-3\"><div><h2 class=\"fw-bold fs-2\" style=\"color: #8b5cf6;\"><i class=\"bi bi-speedometer2 me-2\"></i>Dashboard Admin</h2><p class=\"m-0\" style=\"color: #9ca3af;\">Selamat datang kembali, <strong style=\"color:white;\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(user.Name)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/admin/dashboard.templ`, Line: 25, Col: 68}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</strong>!</p></div><a href=\"/invitation/create\" class=\"btn-primary-custom\"><i class=\"bi bi-plus-circle me-2\"></i>Buat Undangan</a></div><!-- STATS CARDS - UTAMA --><div class=\"row g-3 mb-4\"><div class=\"col-6 col-md-3\"><div class=\"p-3 text-center\" style=\"background:#1e1e1e; border-radius:16px; border:1px solid #2a2a2a; border-top:4px solid #8b5cf6;\"><i class=\"bi bi-envelope-paper fs-2 mb-2\" style=\"color:#8b5cf6;\"></i><h6 class=\"mb-1\" style=\"color:#9ca3af; font-size:0.75rem;\">Total Project</h6><h2 class=\"fw-bold mb-0\" style=\"color:white; font-size:2rem;\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var3 string
		templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(formatNumber(totalProjects))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/admin/dashboard.templ`, Line: 39, Col: 95}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</h2></div></div><div class=\"col-6 col-md-3\"><div class=\"p-3 text-center\" style=\"background:#1e1e1e; border-radius:16px; border:1px solid #2a2a2a; border-top:4px solid #f59e0b;\"><i class=\"bi bi-pencil-square fs-2 mb-2\" style=\"color:#f59e0b;\"></i><h6 class=\"mb-1\" style=\"color:#9ca3af; font-size:0.75rem;\">Draft</h6><h2 class=\"fw-bold mb-0\" style=\"color:white; font-size:2rem;\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var4 string
		templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinStringErrs(formatNumber(totalDraft))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/admin/dashboard.templ`, Line: 47, Col: 92}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "</h2></div></div><div class=\"col-6 col-md-3\"><div class=\"p-3 text-center\" style=\"background:#1e1e1e; border-radius:16px; border:1px solid #2a2a2a; border-top:4px solid #10b981;\"><i class=\"bi bi-check-circle fs-2 mb-2\" style=\"color:#10b981;\"></i><h6 class=\"mb-1\" style=\"color:#9ca3af; font-size:0.75rem;\">Published</h6><h2 class=\"fw-bold mb-0\" style=\"color:white; font-size:2rem;\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var5 string
		templ_7745c5c3_Var5, templ_7745c5c3_Err = templ.JoinStringErrs(formatNumber(totalPublished))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/admin/dashboard.templ`, Line: 55, Col: 96}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var5))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "</h2></div></div><div class=\"col-6 col-md-3\"><div class=\"p-3 text-center\" style=\"background:#1e1e1e; border-radius:16px; border:1px solid #2a2a2a; border-top:4px solid #ec489a;\"><i class=\"bi bi-envelope-check fs-2 mb-2\" style=\"color:#ec489a;\"></i><h6 class=\"mb-1\" style=\"color:#9ca3af; font-size:0.75rem;\">Total RSVP</h6><h2 class=\"fw-bold mb-0\" style=\"color:white; font-size:2rem;\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var6 string
		templ_7745c5c3_Var6, templ_7745c5c3_Err = templ.JoinStringErrs(formatNumber(totalRsvp))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/admin/dashboard.templ`, Line: 63, Col: 91}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var6))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "</h2></div></div></div><!-- STATS CARDS - SECONDARY --><div class=\"row g-3 mb-4\"><div class=\"col-6 col-md-3\"><div class=\"p-3 d-flex align-items-center gap-3\" style=\"background:#1e1e1e; border-radius:12px; border:1px solid #2a2a2a;\"><div style=\"width:42px; height:42px; background:rgba(139,92,246,0.1); border-radius:10px; display:flex; align-items:center; justify-content:center;\"><i class=\"bi bi-eye\" style=\"color:#8b5cf6; font-size:1.2rem;\"></i></div><div><div style=\"color:#9ca3af; font-size:0.7rem;\">Total Views</div><div style=\"color:white; font-weight:700; font-size:1.1rem;\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var7 string
		templ_7745c5c3_Var7, templ_7745c5c3_Err = templ.JoinStringErrs(formatNumber(totalViews))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/admin/dashboard.templ`, Line: 77, Col: 92}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var7))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "</div></div></div></div><div class=\"col-6 col-md-3\"><div class=\"p-3 d-flex align-items-center gap-3\" style=\"background:#1e1e1e; border-radius:12px; border:1px solid #2a2a2a;\"><div style=\"width:42px; height:42px; background:rgba(16,185,129,0.1); border-radius:10px; display:flex; align-items:center; justify-content:center;\"><i class=\"bi bi-people\" style=\"color:#10b981; font-size:1.2rem;\"></i></div><div><div style=\"color:#9ca3af; font-size:0.7rem;\">Total Client</div><div style=\"color:white; font-weight:700; font-size:1.1rem;\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var8 string
		templ_7745c5c3_Var8, templ_7745c5c3_Err = templ.JoinStringErrs(formatNumber(totalClients))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/admin/dashboard.templ`, Line: 89, Col: 94}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var8))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, "</div></div></div></div><div class=\"col-6 col-md-3\"><div class=\"p-3 d-flex align-items-center gap-3\" style=\"background:#1e1e1e; border-radius:12px; border:1px solid #2a2a2a;\"><div style=\"width:42px; height:42px; background:rgba(59,130,246,0.1); border-radius:10px; display:flex; align-items:center; justify-content:center;\"><i class=\"bi bi-person-badge\" style=\"color:#3b82f6; font-size:1.2rem;\"></i></div><div><div style=\"color:#9ca3af; font-size:0.7rem;\">Total Staff</div><div style=\"color:white; font-weight:700; font-size:1.1rem;\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var9 string
		templ_7745c5c3_Var9, templ_7745c5c3_Err = templ.JoinStringErrs(formatNumber(totalStaff))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/admin/dashboard.templ`, Line: 101, Col: 92}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var9))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 9, "</div></div></div></div><div class=\"col-6 col-md-3\"><div class=\"p-3 d-flex align-items-center gap-3\" style=\"background:#1e1e1e; border-radius:12px; border:1px solid #2a2a2a;\"><div style=\"width:42px; height:42px; background:rgba(139,92,246,0.1); border-radius:10px; display:flex; align-items:center; justify-content:center;\"><i class=\"bi bi-layout-three-columns\" style=\"color:#8b5cf6; font-size:1.2rem;\"></i></div><div><div style=\"color:#9ca3af; font-size:0.7rem;\">Total Template</div><div style=\"color:white; font-weight:700; font-size:1.1rem;\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var10 string
		templ_7745c5c3_Var10, templ_7745c5c3_Err = templ.JoinStringErrs(formatNumber(totalTemplates))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/admin/dashboard.templ`, Line: 113, Col: 96}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var10))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 10, "</div></div></div></div></div><!-- RECENT PROJECTS --><div class=\"mb-4\" style=\"background:#1e1e1e; border-radius:16px; border:1px solid #2a2a2a; overflow:hidden;\"><div class=\"p-3 d-flex justify-content-between align-items-center\" style=\"border-bottom:1px solid #2a2a2a;\"><h5 class=\"mb-0\" style=\"color:#8b5cf6; font-size:1rem;\"><i class=\"bi bi-clock-history me-2\"></i>Project Terbaru</h5><a href=\"/admin/projects\" style=\"color:#8b5cf6; text-decoration:none; font-size:0.85rem; opacity:0.7;\">Lihat Semua <i class=\"bi bi-arrow-right\"></i></a></div><div class=\"table-responsive\"><table class=\"table mb-0\"><thead><tr><th class=\"ps-3 py-3\">Judul</th><th class=\"py-3\">Client</th><th class=\"py-3\">Status</th><th class=\"py-3\">Dibuat</th></tr></thead> <tbody>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if len(recentProjects) > 0 {
			for _, project := range recentProjects {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 11, "<tr><td class=\"ps-3 py-3\"><div style=\"color:white; font-weight:600;\">")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var11 string
				templ_7745c5c3_Var11, templ_7745c5c3_Err = templ.JoinStringErrs(project.Title)
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/admin/dashboard.templ`, Line: 144, Col: 67}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var11))
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 12, "</div>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				if project.Template != nil {
					templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 13, "<small style=\"color:#6b7280; font-size:0.7rem;\">")
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					var templ_7745c5c3_Var12 string
					templ_7745c5c3_Var12, templ_7745c5c3_Err = templ.JoinStringErrs(project.Template.Name)
					if templ_7745c5c3_Err != nil {
						return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/admin/dashboard.templ`, Line: 146, Col: 81}
					}
					_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var12))
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 14, "</small>")
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 15, "</td><td class=\"py-3\" style=\"color:#9ca3af;\">")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				if project.User != nil {
					var templ_7745c5c3_Var13 string
					templ_7745c5c3_Var13, templ_7745c5c3_Err = templ.JoinStringErrs(project.User.Name)
					if templ_7745c5c3_Err != nil {
						return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/admin/dashboard.templ`, Line: 151, Col: 29}
					}
					_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var13))
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 16, "</td><td class=\"py-3\">")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				if project.Status == "published" {
					templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 17, "<span class=\"badge\" style=\"background:#10b981;\">Published</span>")
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
				} else if project.Status == "draft" {
					templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 18, "<span class=\"badge\" style=\"background:#f59e0b; color:#1a1a1a;\">Draft</span>")
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
				} else {
					templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 19, "<span class=\"badge\" style=\"background:#6b7280;\">Archived</span>")
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 20, "</td><td class=\"py-3\" style=\"color:#6b7280; font-size:0.8rem;\">")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var14 string
				templ_7745c5c3_Var14, templ_7745c5c3_Err = templ.JoinStringErrs(project.CreatedAt.Format("02/01/2006"))
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/admin/dashboard.templ`, Line: 164, Col: 49}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var14))
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 21, "</td></tr>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
		} else {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 22, "<tr><td colspan=\"4\" class=\"text-center py-5\" style=\"color:#6b7280;\"><i class=\"bi bi-inbox fs-3 d-block mb-2\"></i> Belum ada project</td></tr>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 23, "</tbody></table></div></div><!-- INFO AKUN --><div class=\"p-4\" style=\"background:#1e1e1e; border-radius:16px; border:1px solid #2a2a2a;\"><h5 class=\"fw-bold mb-3\" style=\"color:#8b5cf6; font-size:1rem;\"><i class=\"bi bi-info-circle me-2\"></i>Informasi Akun</h5><div class=\"row g-3\"><div class=\"col-12 col-md-6\"><div class=\"d-flex justify-content-between py-2\" style=\"border-bottom:1px solid #2a2a2a;\"><span style=\"color:#9ca3af;\">Nama</span> <span style=\"color:white;\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var15 string
		templ_7745c5c3_Var15, templ_7745c5c3_Err = templ.JoinStringErrs(user.Name)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/admin/dashboard.templ`, Line: 190, Col: 43}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var15))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 24, "</span></div></div><div class=\"col-12 col-md-6\"><div class=\"d-flex justify-content-between py-2\" style=\"border-bottom:1px solid #2a2a2a;\"><span style=\"color:#9ca3af;\">Email</span> <span style=\"color:white;\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var16 string
		templ_7745c5c3_Var16, templ_7745c5c3_Err = templ.JoinStringErrs(user.Email)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/admin/dashboard.templ`, Line: 196, Col: 44}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var16))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 25, "</span></div></div><div class=\"col-12 col-md-6\"><div class=\"d-flex justify-content-between py-2\" style=\"border-bottom:1px solid #2a2a2a;\"><span style=\"color:#9ca3af;\">Role</span> <span class=\"badge\" style=\"background:#8b5cf6;\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var17 string
		templ_7745c5c3_Var17, templ_7745c5c3_Err = templ.JoinStringErrs(user.Role)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/admin/dashboard.templ`, Line: 202, Col: 64}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var17))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 26, "</span></div></div></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
